// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aoehdswoisyhwtsjkfwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvZWhkc3dvaXN5aHd0c2prZndvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjM2ODUsImV4cCI6MjA3MDkzOTY4NX0.7Uh1SJiG3riWGQGRKeIgZc6HDXmWb3c84jZ9_rIE0d8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});